import { Box } from '@mui/material'
import React from 'react'

const Home = () => {
  return (
    <div color='red'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident error, perspiciatis velit assumenda repellat reprehenderit explicabo facilis iste. Amet architecto laborum ad id harum accusamus, omnis placeat illum molestias odio? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam nobis error ratione odit quas reiciendis aut qui culpa dignissimos, neque laudantium aperiam et iste, assumenda, nihil asperiores. Iusto veritatis architecto repudiandae recusandae. Illo ex accusamus error fugit quo voluptas neque consectetur doloribus voluptatibus labore, soluta velit iure voluptatem itaque, harum dolores excepturi? Mollitia debitis eum omnis animi doloribus. Dicta facilis magni est aperiam alias provident molestias voluptatibus saepe necessitatibus molestiae error, tenetur officia reprehenderit esse sunt accusamus iure. Unde aliquid modi consectetur ullam dicta sapiente alias, officiis, incidunt error labore perspiciatis voluptas fuga excepturi est omnis, rem quam assumenda ex ab. Maxime, recusandae aliquid. Ut consectetur enim incidunt quas placeat perspiciatis quos velit. Cumque asperiores pariatur ea et expedita consequatur neque ullam ut. Rerum reprehenderit nemo error illo expedita, dicta sit ad numquam tenetur laudantium temporibus fugit blanditiis voluptate et nostrum? Tempora maiores facere dicta, esse consectetur ex aspernatur illum, et fugiat voluptatum quia quidem magni totam? Qui distinctio, assumenda, placeat possimus aut nemo quia in explicabo atque totam dolorum beatae repellat voluptas id. Harum quasi dicta non iusto, cum ipsam, ex pariatur, repellendus nam veritatis a aliquid eum dignissimos nihil dolorum eaque tempora ipsa. Debitis culpa saepe nisi unde!</div>
  )
}

export default Home